CREATE TABLE STUDENT (
STUDENT_ID NUMBER(7) NOT NULL,
STUDENT_NAME VARCHAR2(10) );
INSERT INTO STUDENT(STUDENT_ID,STUDENT_NAME)VALUES (&STUDENT_ID , '&STUDENT_NAME');
SELECT * from STUDENT;

create table QUALIFIED1(
FACULTYID NUMBER(7) NOT NULL ,
COURSEID VARCHAR2(20) NOT NULL ,
DATEQUALIFIED DATE );
SELECT * from QUALIFIED1;
INSERT INTO QUALIFIED1(FACULTYID,COURSEID,DATEQUALIFIED) values (&FACULTYID , '&COURSEID');

CREATE TABLE FACULTY(
FACULTYID NUMBER(7) NOT NULL,
FACULTYNAME VARCHAR2(10) NOT NULL);
INSERT INTO FACULTY (FACULTYID , FACULTYNAME) values  (&FACULTYID , '&FACULTYNAME');
SELECT * from FACULTY;

CREATE TABLE SECTION(
SECTION_NO NUMBER (10) NOT NULL,
SEMESTER VARCHAR2 (10) NOT NULL,
COURSE_ID VARCHAR2 (20) NOT NULL) ;
INSERT INTO SECTION ( SECTION_NO , SEMESTER , COURSE_ID) values (&SECTION_NO , '&SEMESTER');
SELECT * from SECTION;

CREATE TABLE COURSE (
COURSE_ID NUMBER (10) NOT NULL,
COURSE_NAME VARCHAR2 (20) );