CREATE TABLE Students(
REGNO VARCHAR(20) PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
FATHER_NAME VARCHAR(50),
ADDRESS VARCHAR(50),
CGPA FLOAT(4)
);
ALTER TABLE Students
ADD CONSTRAINT uc_personID UNIQUE (REGNO)