CREATE TABLE EMPLOYEE11 (
    EMP_ID INT PRIMARY KEY,
    FNAME VARCHAR(50),
    LNAME VARCHAR(50),
    HIREDATE DATE,
    ADDRESS VARCHAR(100),
    SALARY DECIMAL(10, 2)
);
INSERT INTO EMPLOYEE11 (EMP_ID, FNAME, LNAME, HIREDATE, ADDRESS, SALARY) VALUES  (7499, 'ALLEN', 'SALESMAN', DATE '1981-02-20', 'Address2', 1600);
INSERT INTO EMPLOYEE11 (EMP_ID, FNAME, LNAME, HIREDATE, ADDRESS, SALARY) VALUES   (7521, 'WARD', 'SALESMAN', DATE '1981-02-22', 'Address3', 1250);
INSERT INTO EMPLOYEE11 (EMP_ID, FNAME, LNAME, HIREDATE, ADDRESS, SALARY) VALUES   (7566, 'JONES', 'MANAGER', DATE '1981-04-02', 'Address4', 2975);
INSERT INTO EMPLOYEE11 (EMP_ID, FNAME, LNAME, HIREDATE, ADDRESS, SALARY) VALUES   (7654, 'MARTIN', 'SALESMAN',DATE  '1981-09-28', 'Address5', 1250);
INSERT INTO EMPLOYEE11 (EMP_ID, FNAME, LNAME, HIREDATE, ADDRESS, SALARY) VALUES  (7698, 'BLAKE', 'MANAGER', DATE '1981-05-01', 'Address6', 2850);
INSERT INTO EMPLOYEE11 (EMP_ID, FNAME, LNAME, HIREDATE, ADDRESS, SALARY) VALUES  (7782, 'CLARK', 'MANAGER', DATE '1981-06-09', 'Address7', 2450);
INSERT INTO EMPLOYEE11 (EMP_ID, FNAME, LNAME, HIREDATE, ADDRESS, SALARY) VALUES (7788, 'SCOTT', 'ANALYST', DATE '1982-12-09', 'Address8', 3000);
INSERT INTO EMPLOYEE11 (EMP_ID, FNAME, LNAME, HIREDATE, ADDRESS, SALARY) VALUES (7839, 'KING', 'PRESIDENT', DATE '1981-11-17', 'Address9', 5000);
INSERT INTO EMPLOYEE11 (EMP_ID, FNAME, LNAME, HIREDATE, ADDRESS, SALARY) VALUES  (7844, 'TURNER', 'SALESMAN',DATE  '1981-09-08', 'Address10', 1500);
INSERT INTO EMPLOYEE11 (EMP_ID, FNAME, LNAME, HIREDATE, ADDRESS, SALARY) VALUES (7876, 'ADAMS', 'CLERK', DATE '1983-01-12', 'Address11', 1100);
INSERT INTO EMPLOYEE11 (EMP_ID, FNAME, LNAME, HIREDATE, ADDRESS, SALARY) VALUES  (7900, 'JAMES', 'CLERK', DATE '1981-12-03', 'Address12', 950);
INSERT INTO EMPLOYEE11 (EMP_ID, FNAME, LNAME, HIREDATE, ADDRESS, SALARY) VALUES  (7902, 'FORD', 'ANALYST', DATE '1981-12-03', 'Address13', 3000);
INSERT INTO EMPLOYEE11 (EMP_ID, FNAME, LNAME, HIREDATE, ADDRESS, SALARY) VALUES (7934, 'MILLER', 'CLERK', DATE '1982-01-23', 'Address14', 1300);

SELECT * FROM EMPLOYEE11;

SELECT * FROM EMPLOYEE11 WHERE EXTRACT(MONTH FROM HIREDATE) = 1;

SELECT * FROM EMPLOYEE11 WHERE EXTRACT(YEAR FROM HIREDATE) = 1986;

SELECT * FROM EMPLOYEE11
WHERE EXTRACT(YEAR FROM HIREDATE) >= 1950
  AND EXTRACT(YEAR FROM HIREDATE) <= 1959;
  
SELECT FNAME, LNAME, SALARY
FROM EMPLOYEE11
WHERE TO_CHAR(HIREDATE, 'YY') IN ('86', '13', '14');

SELECT CONCAT(UPPER(SUBSTR(FNAME, 1, 1)), '.', UPPER(SUBSTR(LNAME, 1, 1)), ' ',
              TO_CHAR(HIREDATE, 'DDth MON NINETEEN YY')) AS "Employee Info"
FROM EMPLOYEE11;

SELECT CONCAT(UPPER(FNAME), ' ', TO_CHAR(HIREDATE, 'DDth MON NINETEEN YY')) AS "Employee Info"
FROM EMPLOYEE11;

SELECT CONCAT(FNAME, ' ', TO_CHAR(HIREDATE, 'DAY')) AS "Employee Info"
FROM EMPLOYEE11;

SELECT CONCAT(FNAME, ' ', TO_CHAR(HIREDATE, 'DD/MM/YY')) AS "Employee Info"
FROM EMPLOYEE11;
-- short quiz --
SELECT FNAME,
       MONTHS_BETWEEN(TO_DATE(SYSDATE,'YYYY-MON-DD'),TO_DATE( HIREDATE , 'YYYY-MON-DD')) AS MONTHS_WORKED
FROM EMPLOYEE11; -- Replace YourTableName with the actual name of your table

SELECT EMP_ID,FNAME,HIREDATE
FROM EMPLOYEE11
WHERE EXTRACT(YEAR FROM HIREDATE) = 1981;

SELECT EMP_ID,FNAME,HIREDATE
FROM EMPLOYEE11
WHERE EXTRACT(MONTH FROM HIREDATE) != 3;


SELECT EMP_ID, FNAME,
       TO_CHAR(HIREDATE, 'DDth MON ''NINETEEN'' YY') AS FORMATEDHIRE_DATE
FROM EMPLOYEE11;



