CREATE TABLE orders001 (
  order_id number(5),
  quantity number(4),
  cost_per_item number(6,2),
  total_cost number(8,2),
  create_date date,
  created_by varchar2(10)
);
CREATE OR REPLACE TRIGGER orders_before_insert001
BEFORE INSERT
ON orders001
FOR EACH ROW
DECLARE
  v_username varchar2(10);
BEGIN
  -- Find username of the person performing INSERT into the table
  SELECT user INTO v_username FROM dual;
  -- Update create_date field to the current system date
  :new.create_date := sysdate;
  -- Update created_by field to the username of the person performing the INSERT
  :new.created_by := v_username;
END;
-- Corrected INSERT statement
INSERT INTO orders001(order_id, quantity, cost_per_item, total_cost)VALUES (1, 10, 100, 1000);
-- Check the inserted data
SELECT * FROM orders001;


-- example 02---
-- Creating the orders table
CREATE TABLE orders221
(
  order_id number(5),
  quantity number(4),
  cost_per_item number(6,2),
  total_cost number(8,2)
);
INSERT INTO orders221 (order_id, quantity, cost_per_item, total_cost)VALUES (1, 10, 100, 1000);
SELECT * FROM orders221;
-- Creating the orders_audit table for auditing
CREATE TABLE orders_audit
(
  audit_id number(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  order_id number(5),
  quantity number(4),
  cost_per_item number(6,2),
  total_cost number(8,2),
  username varchar2(10),
  audit_timestamp timestamp DEFAULT CURRENT_TIMESTAMP
);

-- Creating the AFTER INSERT trigger
CREATE OR REPLACE TRIGGER orders_after_insert0101
AFTER INSERT ON orders221
FOR EACH ROW
DECLARE
  v_username varchar2(10);
BEGIN
  -- Find username of person performing the INSERT into the table
  SELECT user INTO v_username FROM dual;

  -- Insert record into audit table
  INSERT INTO orders_audit
  (
    order_id,
    quantity,
    cost_per_item,
    total_cost,
    username
  )
  VALUES
  (
    :new.order_id,
    :new.quantity,
    :new.cost_per_item,
    :new.total_cost,
    v_username
  );
END;
-- Example insert into orders20

SELECT * FROM orders_audit;

