CREATE TABLE Birthday(
bname VARCHAR2(50),
bday VARCHAR2(50)
);
SELECT * FROM Birthday;
INSERT INTO Birthday (bname ,bday) VALUES ('Aroosha' , TO_DATE('23-05-2005 12:59:59 A.M.' , 'DD-MON-YY HH:MI:SS A.M.'));
INSERT INTO Birthday (bname, bday) VALUES ('ANDY',TO_DATE('13-AUG-66 12:56 A.M.','DD-MON-YY HH:MI A.M.')); 
SHOW NEXT_DAY(SYSDATE ,'Tues');
SELECT MONTHS_BETWEEN 
 (TO_DATE('02-02-1996','MM-DD-YYYY'),
 TO_DATE('02-02-1995','MM-DD-YYYY') ) "Months"
 FROM DUAL;

SELECT UPPER(bname)FROM Birthday;

SELECT CONCAT('Aroosha' , 'Fatima') bname FROM Birthday;

-- Create DEPARTMENT table
CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID NUMBER PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(50) NOT NULL
);
-- Create EMPLOYEE table
CREATE TABLE EMPLOYE(
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR2(100) NOT NULL,
    EMPLOYEE_SALARY NUMBER,
    EMPLOYEE_HIRE_DATE DATE,
    DEPARTMENT_ID NUMBER,
    CONSTRAINT fk_department
        FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENT (DEPARTMENT_ID)
);
-- Insert data into DEPARTMENT table
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME)VALUES (1, 'HR');
INSERT INTO DEPARTMENT (DEPARTMENT_ID, DEPARTMENT_NAME)VALUES (2, 'IT');
SELECT * FROM DEPARTMENT;
-- Insert data into EMPLOYEE table
INSERT INTO EMPLOYE (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, EMPLOYEE_HIRE_DATE, DEPARTMENT_ID)VALUES (101, 'John Doe', 50000, TO_DATE('2023-01-15', 'YYYY-MM-DD'), 1);
INSERT INTO EMPLOYE (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, EMPLOYEE_HIRE_DATE, DEPARTMENT_ID)VALUES (102, 'Jane Smith', 60000, TO_DATE('2023-02-20', 'YYYY-MM-DD'), 2);
INSERT INTO EMPLOYE (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, EMPLOYEE_HIRE_DATE, DEPARTMENT_ID)VALUES (103, 'Bob Johnson', 55000, TO_DATE('2023-03-10', 'YYYY-MM-DD'), 1);
SELECT * FROM EMPLOYE;
SELECT  DEPARTMENT.DEPARTMENT_ID 
FROM EMPLOYE INNER JOIN DEPARTMENT
ON DEPARTMENT.DEPARTMENT_ID=EMPLOYE.DEPARTMENT_ID;
