/*CREATE TABLE P00__ (
  P_ID INT,
  LastName VARCHAR(255),
  FirstName VARCHAR(255),
  Address VARCHAR(255),
  City VARCHAR(255) DEFAULT 'TAXILA'
);
CREATE TABLE s
(
P_Id int NOT NULL,
LastName varchar(255) NOT NULL,
FirstName varchar(255),
Address varchar(255),
City varchar(255) DEFAULT 'Sandnes'
);
SELECT * FROM s;
INSERT INTO P00__(P_ID,LastName , FirstName , Address , City) values (&P_ID, '&LastName' , '&FirstName' , '&Address' , '&City');
SELECT P_ID , LastName || FirstName AS NAME
FROM s;

-- Create the Persons table
CREATE TABLE Persons00 (
  P_Id INT,
  LastName VARCHAR(255),
  FirstName VARCHAR(255),
  Address VARCHAR(255),
  City VARCHAR(255)
);
SELECT * FROM Persons00;
INSERT INTO Persons00 (P_Id, LastName, FirstName, Address, City) VALUES (1, 'Hansen', 'Ola', 'Timoteivn 10', 'Sandnes');
INSERT INTO Persons00 (P_Id, LastName, FirstName, Address, City) VALUES  (2, 'Svendson', 'Tove', 'Borgvn 23', 'Sandnes');
INSERT INTO Persons00 (P_Id, LastName, FirstName, Address, City) VALUES (3, 'Pettersen', 'Kari', 'Storgt 20', 'Stavanger');
SELECT DISTINCT City 
FROM Persons00;
SELECT * FROM Persons00 
WHERE LastName ='Svendson'AND ( FirstName='Tove' OR FirstName='Ola');
SELECT * FROM Persons00
ORDER BY Lastname ASC;
SELECT * FROM Persons00
WHERE City
BETWEEN 'Stavanger' AND 'Stavanger';
SELECT * FROM Persons00
WHERE LastName
NOT BETWEEN 'Hansen' AND 'Pettersen'
*/
CREATE TABLE EMP1 (
  EMPNO NUMBER(4) PRIMARY KEY,
  ENAME VARCHAR2(10),
  E_JOB VARCHAR2(9),
  MGR NUMBER(4),
  HIREDATE DATE,
  SAL NUMBER(7, 2),
  COMM NUMBER(7, 2),
  DEPTNO NUMBER(2)
);
INSERT INTO EMP1 (EMPNO, ENAME, E_JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES(7369, 'SMITH', 'CLERK', 7902, TO_DATE('17-Dec-80', 'DD-Mon-YY'), 800, NULL, 20);
INSERT INTO EMP1(EMPNO, ENAME, E_JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES(7499, 'ALLEN', 'SALESMAN', 7698, TO_DATE('20-Feb-81', 'DD-Mon-YY'), 1600, 300, 30);
INSERT INTO EMP1 (EMPNO, ENAME, E_JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7521, 'WARD', 'SALESMAN', 7698, TO_DATE('22-Feb-81', 'DD-Mon-YY'), 1250, 500, 30);
INSERT INTO EMP1 (EMPNO, ENAME, E_JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7566, 'JONES', 'MANAGER', 7839, TO_DATE('02-Apr-81', 'DD-Mon-YY'), 2975, NULL, 20);
INSERT INTO EMP1 (EMPNO, ENAME, E_JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7654, 'MARTIN', 'SALESMAN', 7698, TO_DATE('28-Sep-81', 'DD-Mon-YY'), 1250, 1400, 30);
INSERT INTO EMP1 (EMPNO, ENAME, E_JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7698, 'BLAKE', 'MANAGER', 7839, TO_DATE('01-May-81', 'DD-Mon-YY'), 2850, NULL, 30);
INSERT INTO EMP1 (EMPNO, ENAME, E_JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7782, 'CLARK', 'MANAGER', 7839, TO_DATE('09-Jun-81', 'DD-Mon-YY'), 2450, NULL, 10);
INSERT INTO EMP1 (EMPNO, ENAME, E_JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES  (7788, 'SCOTT', 'ANALYST', 7566, TO_DATE('09-Dec-82', 'DD-Mon-YY'), 3000, NULL, 20);
INSERT INTO EMP1 (EMPNO, ENAME, E_JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (7839, 'KING', 'PRESIDENT', NULL, TO_DATE('17-Nov-81', 'DD-Mon-YY'), 5000, NULL, 10);
INSERT INTO EMP1 (EMPNO, ENAME, E_JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES(7844, 'TURNER', 'SALESMAN', 7698, TO_DATE('08-Sep-81', 'DD-Mon-YY'), 1500, 0, 30);
INSERT INTO EMP1 (EMPNO, ENAME, E_JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES(7876, 'ADAMS', 'CLERK', 7788, TO_DATE('12-Jan-83', 'DD-Mon-YY'), 1100, NULL, 20);
INSERT INTO EMP1 (EMPNO, ENAME, E_JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES(7900, 'JAMES', 'CLERK', 7698, TO_DATE('03-Dec-81', 'DD-Mon-YY'), 950, NULL, 30);
INSERT INTO EMP1 (EMPNO, ENAME, E_JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES(7902, 'FORD', 'ANALYST', 7566, TO_DATE('03-Dec-81', 'DD-Mon-YY'), 3000, NULL, 20);
INSERT INTO EMP1 (EMPNO, ENAME, E_JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES(7934, 'MILLER', 'CLERK', 7782, TO_DATE('23-Jan-82', 'DD-Mon-YY'), 1300, NULL, 10);

SELECT * FROM EMP1;
SELECT  MIN(SAL) AS Minimum
FROM EMP1;
SELECT MAX(SAL) AS Maximum
FROM EMP1;
SELECT AVG(SAL) AS Average
FROM EMP1;
SELECT SUM(SAL) AS Sum
FROM EMP1;

SELECT E_JOB ,
MIN(SAL) AS Minimum,
MAX(SAL) AS Maximum,
AVG(SAL) AS Average,
SUM(SAL) AS Sum 
FROM EMP1
GROUP BY E_JOB;









